---
- name: Install Docker
  hosts: VMsG
  become: yes

  tasks:
  - name: Add Docker repository key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker repository
    apt_repository: repo='deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' state=present
  - name: Update apt
    apt: update_cache=yes
  - name: Install Docker
    apt:
      pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin
      state: present
  
      