---
- name: Start Grafana in Docker
  hosts: VMsG
  become: yes

  tasks:
  - name: Install python3-pip
    apt:
     name: pip
  - name: Install python docker module
    pip:
     name: docker       
  - name: Start grafana container
    docker_container:
     name: mygrafana
     image: grafana/grafana
     detach: yes
     network_mode: host

