---
# tasks file for start_grafana_indocker
- name: Start grafana container
  docker_container:
   name: mygrafana
   image: grafana/grafana
   detach: yes
   network_mode: host
   restart_policy: always
