---
# tasks file for users_nopasswd_authkey
- name: Create group
  group:
    name: '{{ group }}'
    state: present
- name: Create some users
  user:
    name: '{{ item.name }}'
    shell: '{{ item.shell }}'
    groups: '{{ item.groups }}'
    append: yes
  with_items: '{{ user_details }}'
- name: Add to authorized_keys
  authorized_key:
    user: '{{ item.name }}'
    state: present
    key: "{{ lookup('file', '{{ src_path }}/{{ item.name }}.pub') }}"
  with_items: '{{ user_details }}'
- name: Set no passwd for group
  lineinfile:
    path: '{{ path_sudoers_file }}'
    line: '{{ group_nopasswd }}'
    validate: 'visudo -cf %s'
    state: present
  
